name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: release-please-action

      - uses: actions/checkout@v3
        name: Checkout OpenAPI specification repository
        with:
          path: gentrace-openapi
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"
          cache-dependency-path: gentrace-openapi/yarn.lock
        if: ${{ steps.release.outputs.release_created }}

      - name: ⎔ Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.7.0
        if: ${{ steps.release.outputs.release_created }}

      - name: Install and generate (OpenAPI)
        run: |
          cd $GITHUB_WORKSPACE/gentrace-openapi
          yarn install

          # Assumes that all generated repositories are at relative path "../<original-repo-name>" 
          yarn build
        if: ${{ steps.release.outputs.release_created }}

      - name: Run Prettier
        id: prettier
        run: |
          cd $GITHUB_WORKSPACE/gentrace-openapi
          npx prettier --check spec.yaml || (
            echo "::set-output name=prettier_failed::true"
          )
        if: ${{ steps.release.outputs.release_created }}

      - name: Fail if Prettier found issues
        if: ${{ steps.release.outputs.release_created }} && ${{ steps.prettier.outputs.prettier_failed == 'true' }}
        run: exit 1
